FROM golang:1.19-alpine
ENV CGO_ENABLED 0

RUN apk update && apk add bash inotify-tools git

RUN mkdir /build
WORKDIR /build

# installing Delve debugger
ENV GO111MODULE=on
RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go install github.com/cespare/reflex@latest

# build micro-service binary
COPY . .

EXPOSE 8080 40000

ENTRYPOINT sh startScript.sh