version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.Debug
    image: app
    container_name: app
    restart: unless-stopped
    env_file: .env
    environment:
      - IS_DOCKER=TRUE
    ports:
      - "40000:40000"
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=oscarllamas6
      - MONGO_INITDB_ROOT_PASSWORD=golang2023
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - ./dbdata:/data/db

volumes:
  dbdata:

networks:
  my_network:
    driver: bridge
    name: my_network
